[secrets]

[[secrets.ruleset]]
[secrets.ruleset.identifier]
type = "gitleaks_rule_id"
value = "default_rules"

[[secrets.ruleset]]
[secrets.ruleset.identifier]
type = "gitleaks_rule_id"
value = "custom_rules"

# Define your custom rules here
[[secrets.ruleset]]
[secrets.ruleset.identifier]
type = "gitleaks_rule_id"
value = "custom_log_rule"
[secrets.ruleset.override]
description = "Custom log detection rule"
regex = '''Your custom regex pattern'''
